package tid.bgp.bgp4.update.fields.pathAttributes;

import tid.bgp.bgp4.update.fields.PathAttribute;


/**
 * ORIGIN is a well-known mandatory attribute.  The ORIGIN attribute is
   generated by the speaker that originates the associated routing
   information.  Its value SHOULD NOT be changed by any other speaker.
   
 *   a) ORIGIN (Type Code 1):

            ORIGIN is a well-known mandatory attribute that defines the
            origin of the path information.  The data octet can assume
            the following values:

               Value      Meaning

               0         IGP - Network Layer Reachability Information
                            is interior to the originating AS

               1         EGP - Network Layer Reachability Information
                            learned via the EGP protocol [RFC904]

               2         INCOMPLETE - Network Layer Reachability
                            Information learned by some other means
                            
 * @author mcs
 *
 */
public class OriginAttribute extends PathAttribute{

	int value;
	
	public OriginAttribute(){		
		super();
		//Poner los flags. 		
		this.typeCode = PathAttributesTypeCode.PATH_ATTRIBUTE_TYPECODE_ORIGIN;

	}
	public OriginAttribute(byte []bytes, int offset){
		super(bytes, offset);
		decode(bytes,offset+mandatoryLength);		
	}
	@Override
	public void encode() {
		log.info("Origin Attribute");
		pathAttributeLength = 1;
		this.length=pathAttributeLength+mandatoryLength;

		this.bytes=new byte[this.length];
		encodeHeader();		
		bytes[3]=(byte)(value & 0xFF);		
		
	}
	public void decode(byte []bytes, int offset){
		value = bytes[offset];
	}
	public int getValue() {
		return value;
	}
	public void setValue(int value) {
		this.value = value;
	}
	
	@Override
	public String toString() {
		//String sb = super.toString();
		return "Origin [Value=" + value+ "]";
	}
	

}
